spring:
  #数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/rul_blog?serverTimezone=UTC
    username: root
    password: "03290221"
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 10 #初始化连接数
      min-idle: 8 #最小空闲连接数
      max-active: 12 #最大活跃连接数

  #redis配置
  redis:
    host: localhost
    port: 6379
    timeout: 2000


#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.rul.blog.pojo